#!/usr/bin/with-contenv bash

mkdir -p /config

if [ ! -f "/config/settings.json" ]; then
	cp /defaults/settings.json /config/settings.json
fi

ln -sf /config /root/.duplicacy-web

chmod 711 /root

# permissions
chown -R abc:abc \
	/root/.duplicacy-web \
	/data \
	/config \
	/app/duplicacy
